name: palette_swap_tool
description: A simple tool for generating palette swap LUTs for use in palette swap shaders, etc.

publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.10
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.3.6
  image: ^3.2.0
  freezed_annotation: ^2.0.3
  hive_generator: ^2.0.0
  bitsdojo_window: ^0.1.2
  dynamic_color: ^1.4.0
  http: ^1.1.0
  version: ^3.0.2
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true