name: Flutter CI

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "lib/**"
      - "linux/**"
      - "macos/**"
      - "windows/**"
      - "test/**"
      - "pubspec.lock"
      - "pubspec.yaml"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Set build name conditionally
      - name: Set Build name
        run: |
          case $GITHUB_REF in
            "refs/tags/"*) echo "BUILD_NAME=${GITHUB_REF/refs\/tags\/v}" >> $GITHUB_ENV ;;
            *) echo "BUILD_NAME='0.0.0'" >> $GITHUB_ENV ;;
          esac
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.6'
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release -v --dart-define BUILD_NAME=$BUILD_NAME
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: palette_swap_tool-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle
      # Upload artifact so we can test intermediate builds without tagging a release
      - uses: actions/upload-artifact@v3
        with:
          name: linux
          path: build/linux/x64/release/bundle/palette_swap_tool-${{github.ref_name}}-linux.zip
      - name: Linux Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/linux/x64/release/bundle/palette_swap_tool-${{github.ref_name}}-linux.zip
          draft: true

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # Set build name conditionally
      - name: Set Build name
        run: |
          $input = $env:GITHUB_REF;
          $result = switch -Regex ( $input )
          {
              'refs/tags/v'
              {
                  $input | Select-String -Pattern '(refs/tags/v)(.*)' -AllMatches | % {$_.matches.groups[2].value}
              }
              default
              {
                  '0.0.0'
              }
          };
          echo "BUILD_NAME=$result" >> $env:GITHUB_ENV;
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.6'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release -v --build-name=$env:BUILD_NAME --dart-define BUILD_NAME=$env:BUILD_NAME
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: palette_swap_tool-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      # Upload artifact so we can test intermediate builds without tagging a release
      - uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows/runner/Release/palette_swap_tool-${{github.ref_name}}-windows.zip
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/runner/Release/palette_swap_tool-${{github.ref_name}}-windows.zip
          draft: true

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # Set build name conditionally
      - name: Set Build name
        run: |
          case $GITHUB_REF in
            "refs/tags/"*) echo "BUILD_NAME=${GITHUB_REF/refs\/tags\/v}" >> $GITHUB_ENV ;;
            *) echo "BUILD_NAME='0.0.0'" >> $GITHUB_ENV ;;
          esac
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '3.10.6'
      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release -v --build-name=$BUILD_NAME --dart-define BUILD_NAME=$BUILD_NAME
      - name: Move app folder to be zipped alone
        run: |
          mkdir build/macos/Build/Products/Release/zip/
          mv build/macos/Build/Products/Release/palette_swap_tool.app build/macos/Build/Products/Release/zip/palette_swap_tool.app
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: palette_swap_tool-${{github.ref_name}}-macos.zip
          directory: build/macos/Build/Products/Release/zip
      # Upload artifact so we can test intermediate builds without tagging a release
      - uses: actions/upload-artifact@v3
        with:
          name: macos
          path: build/macos/Build/Products/Release/zip/palette_swap_tool-${{github.ref_name}}-macos.zip
      - name: macOS Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/macos/Build/Products/Release/zip/palette_swap_tool-${{github.ref_name}}-macos.zip
          draft: true
